### ISSUE TITLE
create toString methods for databricks DTO classes

### ISSUE THREAD

**Issue by samshuster** [edmunds/databricks-rest-client#17]
Narrative

As an engineer working with the databricks rest clientI'd like meaningful toString methods on all java bean classesSuch that I can easily work with and debug these classes

Implementation Details

Nice to have: use jackson to create toString for DTOs, to match up with annotations, e.g.

//ObjectMapper could come from a constant
 return new ObjectMapper().writeValueAsString(this);

Alternatively, use ReflectionToString from commons-lang:

 return ReflectionToString.toString(this);

**Comment by dvorontsov** [comment]
Consider Lombok project for toString() methods

**Comment by samshuster** [comment]
thanks for the pointer @dvorontsov! I decided to go that route.
