### ISSUE TITLE
Bring ClusterService interface up-to-date

### ISSUE THREAD

**Issue by reillydj** [edmunds/databricks-rest-client#34]
There are a few new methods available in Databricks' Cluster API.

Goal:
Add support for the following methods to the ClusterService
1. pin
2. unpin
3. list node types
4. list zones
5. spark versions
6. permanent delete

**Comment by cornelcreanga** [comment]
@samshuster @javamonkey79  - I need some of this methods - should I open an PR?

**Comment by samshuster** [comment]
yes please @cornelcreanga

**Comment by samshuster** [comment]
should add, you can obviously create a pr for only those that you immediately need, no need to do all of the above.

**Comment by cornelcreanga** [comment]
https://github.com/edmunds/databricks-rest-client/pull/75
