### ISSUE TITLE
Support for RequestMethod PATCH

### ISSUE THREAD

**Issue by jyothikomm** [edmunds/databricks-rest-client#54]
Currently the only request methods supported are GET and POST, need support for PATCH to run rest jobs

**Comment by samshuster** [comment]
Can you point me to what you mean exactly by "run rest jobs"?

Thanks and apologies again that we have not seen this for over 2 months.

**Comment by samshuster** [comment]
thanks, we merged this.

**Comment by jyothikomm** [comment]
> thanks, we merged this.

Thanks
