### ISSUE TITLE
Please remove log4j.xml from the project

### ISSUE THREAD

**Issue by cornelcreanga** [edmunds/databricks-rest-client#57]
Please remove log4j.xml from the project. There is no reason for a project that's going to be included as a library into another one to define its own log4 file. If there are multiple log4 files the classloader will just choose one of them and.

**Comment by samshuster** [comment]
sure this makes sense. Do you want to try and put up a PR for it?

**Comment by cornelcreanga** [comment]
https://github.com/edmunds/databricks-rest-client/pull/60

**Comment by samshuster** [comment]
thanks!
