### ISSUE TITLE
Support SCIM API

### ISSUE THREAD

**Issue by samshuster** [edmunds/databricks-rest-client#62]
We would like to support the following endpoints as part of databricks-rest-client:

https://docs.databricks.com/dev-tools/api/latest/scim.html

**Comment by cornelcreanga** [comment]
Are you working on that right now? If not I can take it.

**Comment by samshuster** [comment]
Please go for it @cornelcreanga!

**Comment by cornelcreanga** [comment]
It seems that Databricks created  their own extension "urn:ietf:params:scim:schemas:extension:workspace:2.0:User" but I can't find any documentation about it. I'll ask them about it.

**Comment by samshuster** [comment]
Ok. Let me know if that turns into a blocker and we could try reaching out
to them on our side too.

**Comment by cornelcreanga** [comment]
Can't name it a blocker as by trial and error I figured out what are the fields/rules - at least most of them. 
I've finished the code/tests, tomorrow (my timezone) I'll create the PR. 
I have the feeling that after Databricks will promote the API from preview to production ready we will have to perform changes (a couple of them) on the implementation...

**Comment by cornelcreanga** [comment]
https://github.com/edmunds/databricks-rest-client/pull/64
