### ISSUE TITLE
Change the initScripts field in NewClusterDTO to be an array

### ISSUE THREAD

**Issue by Charliz** [edmunds/databricks-rest-client#70]
One of our processes failed with an error: `com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of com.edmunds.rest.databricks.DTO.InitScriptInfoDTO out of START_ARRAY token`

According to the Databricks API documentation "init_scripts" is an array of InitScriptInfo. Change the initScripts field in NewClusterDTO to be InitScriptInfoDTO[] to align with Databricks API requirements.

**Comment by samshuster** [comment]
thank you for catching and implementing a fix for this!
