### ISSUE TITLE
Update TerminationCodeDTO according with the last API spec

### ISSUE THREAD

**Issue by cornelcreanga** [edmunds/databricks-rest-client#78]
Some of the codes specified here https://docs.databricks.com/dev-tools/api/latest/clusters.html#clusterterminationreasonterminationcode are not reflected in the TerminationCodeDTO => error on deserialization (*) => the cluster API is not usable.

(*)
Example: 
Cannot deserialize value of type `com.edmunds.rest.databricks.DTO.clusters.TerminationCodeDTO` from String "SPARK_ERROR": not one of the values accepted for Enum class: [CLOUD_PROVIDER_LAUNCH_FAILURE, INIT_SCRIPT_FAILURE, INTERNAL_ERROR, INSTANCE_UNREACHABLE, INSTANCE_POOL_CLUSTER_FAILURE, COMMUNICATION_LOST, REQUEST_REJECTED, INACTIVITY, CLOUD_PROVIDER_SHUTDOWN, USER_REQUEST, TRIAL_EXPIRED, INVALID_ARGUMENT, SPARK_STARTUP_FAILURE, UNEXPECTED_LAUNCH_FAILURE, JOB_FINISHED]

https://github.com/edmunds/databricks-rest-client/pull/77

@samshuster

**Comment by samshuster** [comment]
merged
