### ISSUE TITLE
Allow use of custom HttpRequestExecutor in HttpClient

### ISSUE THREAD

**Issue by travisemichael** [edmunds/databricks-rest-client#79]
Hello, we are currently using the library to make run jobs in our production environment. We need to collect metrics around requests to the Databricks API and we use a custom class extending `HttpRequestExecutor` to accomplish this right now. We had to implement our own extension of the DatabricksRestClientImpl in order to pass in our custom `HttpRequestExecutor` to the `HttpClientBuilder` which led to a lot of duplicated code with the `AbstractDatabricksRestClient#initClient` method since the builder is not accessible before initialization. We would like a way to pass this executor to the builder are willing to contribute to the project to make it happen.

My first thought was to add this executor to the `DatabricksServiceFactory.Builder` class so that it could be set in the `initClient` method, but it does not seem to fit the pattern of all the values in the builder being primitives or strings. Right now I do not see a pattern for passing custom parameters to the `HttpClientBuilder`. Is there a preferred way to accomplish this that I could work on? 

Here is a snippet of the workaround we have implemented:

```
    public CustomDatabricksRestClient(DatabricksServiceFactory.Builder builder, ...) {
        super(builder);
        initClientWithExecutor(builder, ...);
    }

    @Override
    protected void initClient(DatabricksServiceFactory.Builder builder) {
        // No-op init
    }

    private void initClientWithExecutor(DatabricksServiceFactory.Builder builder, ...) {
        CustomHttpRequestExecutor customHttpRequestExecutor = new CustomHttpRequestExecutor(...);

        HttpClientBuilder clientBuilder = HttpClients.custom().useSystemProperties()
                .setRetryHandler(retryHandler)
                .setServiceUnavailableRetryStrategy(retryStrategy)
                .setRequestExecutor(customHttpRequestExecutor)
                .setDefaultRequestConfig(createRequestConfig(builder));

        List<Header> headers = new ArrayList<>();
        if (StringUtils.isNotEmpty(builder.getToken())) {
            Header authHeader = new BasicHeader("Authorization", String.format("Bearer %s", builder.getToken()));
            headers.add(authHeader);
        }

        String userAgent = builder.getUserAgent();
        if (userAgent != null && userAgent.length() > 0) {
            Header userAgentHeader = new BasicHeader("User-Agent", userAgent);
            headers.add(userAgentHeader);
        }

        if (!headers.isEmpty()) {
            clientBuilder.setDefaultHeaders(headers);
        }

        try {
            SSLContext ctx = SSLContext.getDefault();
            // Allow TLSv1.2 protocol only
            SSLConnectionSocketFactory sslsf = new SSLConnectionSocketFactory(
                    ctx,
                    new String[]{"TLSv1.2"},
                    null,
                    SSLConnectionSocketFactory.getDefaultHostnameVerifier());
            clientBuilder = clientBuilder.setSSLSocketFactory(sslsf);
        } catch (Exception e) {
            _log.error("", e);
        }

        client = clientBuilder.build(); //CloseableHttpClient

        url = String.format("https://%s/api/%s", host, apiVersion);
        mapper = new ObjectMapper().setSerializationInclusion(JsonInclude.Include.NON_DEFAULT);
    }
```

**Comment by samshuster** [comment]
hey @travisemichael, first apologies for the delay in getting back to you.

I think I understand the issue and why this would be useful functionality to have. 
What do you think about having it so that an HttpClientBuilder can be passed in? The pros of this is that it would allow people to do a lot of other customization including modifying the HttpExecutor.

**Comment by samshuster** [comment]
hey @travisemichael I took a stab at trying to handle your request above as well as allowing for more configuration if needed. Here is the PR: https://github.com/edmunds/databricks-rest-client/pull/80

Would this be too backwards incompatible for your needs?

**Comment by travisemichael** [comment]
That looks like it would work for our case. The expectation is that we would extend the HttpClientBuilderFactory and override `createClientBuilder` to chain our custom builder parameters after calling `createDefaultClientBuilder` if understand correctly.

The downsides you're talking about would be that the implementation could overwrite params such as the headers/creds etc. right? I don't see any way around that except parameterizing everything that someone would want to set on the `HttpClientBuilder` object but I haven't put that much thought into it.

For backwards compatibility, I'm not too concerned over bumping the version and making the necessary changes.

**Comment by samshuster** [comment]
ok its merged in, tentatively closing this issue. Feel free to re-open if needed
