### ISSUE TITLE
Update (again) TerminationCodeDTO

### ISSUE THREAD

**Issue by cornelcreanga** [edmunds/databricks-rest-client#84]
A new Azure code was added (GLOBAL_INIT_SCRIPT_FAILURE) - not present yet in the documentation. The Jackson deserialization will fail.

In future I think that a better solution would be to convert the unknown enums to null (com.fasterxml.jackson.databind.DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL ) instead of throwing an error. The Azure API seems to change often and it will be hard to keep the pace. 

https://github.com/edmunds/databricks-rest-client/pull/83

@samshuster

**Comment by samshuster** [comment]
hey @cornelcreanga good idea!

**Comment by samshuster** [comment]
hey @cornelcreanga just letting you know that if you use the latest version 3.0.4, the code will now do what you suggest so you won't run into enum exceptions anymore.

**Comment by cornelcreanga** [comment]
tkx @samshuster
