### ISSUE TITLE
databricks-rest-client:3.0.6 - java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by vincentatcompass** [edmunds/databricks-rest-client#93]
databricks-rest-client:3.0.6 introduced log4j 2.17.2... however, a new issue was introduced

```
Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.ClassLoader org.apache.logging.log4j.util.StackLocatorUtil.getCallerClassLoader(int)'
	at org.apache.log4j.Logger.getLogger(Logger.java:40)
	at com.edmunds.rest.databricks.restclient.DefaultHttpClientBuilderFactory.<clinit>(DefaultHttpClientBuilderFactory.java:44)
	at com.edmunds.rest.databricks.DatabricksServiceFactory$Builder.build(DatabricksServiceFactory.java:352)
	at X.X.clients.Databricks.ServiceFactoryByToken(Databricks.java:26)
	at VincentApp.main(VincentApp.java:26)
```

**Comment by vincentatcompass** [comment]
cc @samshuster

**Comment by samshuster** [comment]
hmm are you bringing in other log4j dependencies? That error looks to be caused by another version of log4j on classpath.

**Comment by vincentatcompass** [comment]
I think we do have slf4j from a different library

**Comment by vincentatcompass** [comment]
also, note that log4j-1.2-api will continue to expose the security vulnerability. https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-1.2-api/2.17.2. So, I think it's best if we move away from this API version if possible

**Comment by samshuster** [comment]
got it, ok thanks for explaining. Let me just bite the bullet and update to log4j2, shouldn't be too bad.

**Comment by samshuster** [comment]
Ok 3.1.1 released (upped middle because definitely not backwards compatible, although it sounds like i should have done that for the last release too) 

https://github.com/edmunds/databricks-rest-client/pull/94

It usually takes ~1hr for the release to be available on maven central. I will close once yoou confirm all is good.

**Comment by vincentatcompass** [comment]
@samshuster looks good on my end! thanks for the quick turnaround

**Comment by vincentatcompass** [comment]
Should be good to go. :) Thanks for the quick turnaround!

**Comment by samshuster** [comment]
great thanks @vincentatcompass !
