### ISSUE TITLE
Add support for jobs API 2.1 (multitask jobs)

### ISSUE THREAD

**Issue by Bolshem** [edmunds/databricks-rest-client#98]
Current, it is not possible to configure multiple tasks for one job. However, Databricks Jobs API 2.1 allows that, and this is a feature we would like to use configuring jobs programmatically using the library. Is it possible to add support for that feature?

**Comment by samshuster** [comment]
hey there!
Good call out on this missing functionality. Would you be up for contributing this feature?

**Comment by Bolshem** [comment]
Hey @samshuster . Yes, we are working on adding this, and this should be ready for PR in a week or two. This will require some changes in order to support 2.0 and 2.1 API versions simultaneously (as it is not backward compatible). How can we chat with you about it?

**Comment by samshuster** [comment]
Hey I just looked more into this. Very odd. So I think we will need to refactor so that both versions of the api are supported depending on the service. Is the 2.1 Jobs api backwards compatible at least where we can upgrade the jobs api so that it will still work with all non multi-task jobs? I believe that is the case, probably something worthwhile to test.

**Comment by Bolshem** [comment]
@samshuster I will create Demo PR for upgrading jobs API to 2.1, and leaving everything else @2.0. Jobs API 2.1 is not backward compatible, so the change will break existing code (it is OK for our purposes, not sure if this is the direction you want to go with the official client) - JobSettingsDTO is very different for 2.0 and 2.1.

Next week may work

**Comment by Bolshem** [comment]
@samshuster Just created a PR with new Jobs service for your review

**Comment by samshuster** [comment]
Oh thats too bad. So we will need to make a decision if we just want to no longer support the old api and force an upgrade for anybody using newest client, or somehow support both perhaps with separate factories.

Thank you for that PR, I will take a look at it when I get a chance and then we can figure out a time to talk.
